import type { Metadata } from 'next';
import './globals.css';
import { RootProvider } from './__providers__';
import { AppView } from './__render__';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <RootProvider>
        <AppView>{children}</AppView>
      </RootProvider>
    </html>
  );
}
