import type { Metadata } from "next";
import { Tomorrow } from "next/font/google";
import "./globals.css";
import Footer from "@/ui/Footer";
import Navbar from "@/ui/Navbar";

const tomorrow = Tomorrow({
  variable: "--font-tomorrow",
  subsets: ["latin"],
  weight: [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900",
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${tomorrow.className} antialiased flex w-dvw min-h-dvh flex-col justify-start items-center overflow-x-clip relative bg-gray-900`}
      >
        {/* Background Blobs */}
        <div className="absolute inset-0 -z-10 overflow-hidden">
          {/* Blob 1 */}
          <div className="absolute top-10 left-10 w-72 h-72 bg-orange-400 rounded-full mix-blend-multiply filter blur-3xl opacity-30 animate-pulse animate-float1 sm:w-64 sm:h-64 md:w-80 md:h-80"></div>

          {/* Blob 2 */}
          <div className="absolute top-1/3 right-10 w-72 h-72 bg-orange-600 rounded-full mix-blend-multiply filter blur-3xl opacity-30 animate-pulse animate-float2 sm:w-64 sm:h-64 md:w-80 md:h-80"></div>

          {/* Blob 3 */}
          <div className="absolute bottom-20 left-1/4 w-64 h-64 bg-yellow-400 rounded-full mix-blend-multiply filter blur-3xl opacity-20 animate-pulse animate-float3 sm:w-52 sm:h-52 md:w-64 md:h-64"></div>

          {/* Blob 4 */}
          <div className="absolute bottom-10 right-1/3 w-64 h-64 bg-red-400 rounded-full mix-blend-multiply filter blur-3xl opacity-20 animate-pulse animate-float4 sm:w-52 sm:h-52 md:w-64 md:h-64"></div>
        </div>

        {/* Main Content */}
        <Navbar defaultBg="bg-transparent" mobileMenuBg="bg-[#211b1b]" />
        <main className="flex-1 relative z-10 w-full">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
